### ISSUE TITLE
Chat no guarda cache de conversaciones.

### ISSUE THREAD

**Issue by AxDSan** [Push-EDX/flarum-ext-chat#13]
Me he encontrado con que el chat no guarda el cache de las conversaciones, y si accesas el chat desde otro dispositivo, no obtendras las previas conversaciones y/o conversaciones recientes.

Por tanto me siento un poco perdido cuando estoy siguiendo alguna conversacion y por algun motivo (no estoy en casa etc, etc.) tengo que cambiar de dispositivos temporalmente, se me pierden las conversaciones.

**Comment by gpascualg** [comment]
Ahora mismo en el servidor se guarda el 100% del chat, pero el cliente (tú) cuando se conecta solo recibe las últimos 20 mensajes. Está en mi planes hacer que se pueda cargar mensajes más antiguos (básicamente, si se sube arriba de todo, cargaría nuevos mensajes).

Mis planes son:

- [ ] Extender el chat para incluir un ID para cada mensajes:
  - [ ] Implementar transacciones PDO en el servidor, para evitar inserciones simultáneas y no poder recuperar el ID (https://github.com/Push-EDX/flarum-ext-chat/blob/master/src/Api/Controllers/FetchChatController.php#L73)
  - [ ] Enviar siempre la combinación `(id, actorId, message)` a los clientes, en vez de solo `(actorId, message)` (vease `ChatPost.php`, `ChatPostController`).
  - [ ] El cliente tendŕia que guardar también ese ID, implica pequeños cambios a js/forum`/src/main.js`
- [ ] La API `chat/fetch` deberá además pedir un ID (https://github.com/Push-EDX/flarum-ext-chat/blob/master/src/Api/Controllers/FetchChatController.php#L87)
  - [ ] Donde -1 sería los 20 últimos
  - [ ] Cualquier otro valor el punto des del que cargar

Evidentemente también faltaría toda la parte de UX para el feedback al usuario
- [ ] Subir arriba de todo del chat mostrará un icono de cargando (puede servir el mismo de enviar)

Calculo que esto puede llevar unas 3 horas para hacerse, pero yo ahora estaré de exámenes así que no podré hacerlo hasta la semana que viene

**Comment by AxDSan** [comment]
Vale suena bien, no tengo mucho conocimiento en programacion web pero
estuve mirando la fuente, definitivamente lo que dices suena bien ahora, si
tuviera mayor conocimiento podria ir ayudando implementando algunas de las
cosas que has dicho y asi ayudar en algo en el repositorio jeje bueno pero
al tanto tranquilo que espero xD
On Jun 5, 2016 3:40 PM, "Guillem Pascual Guinovart" <
notifications@github.com> wrote:
>
> Ahora mismo en el servidor se guarda el 100% del chat, pero el cliente
(tú) cuando se conecta solo recibe las últimos 20 mensajes. Está en mi
planes hacer que se pueda cargar mensajes más antiguos (básicamente, si se
sube arriba de todo, cargaría nuevos mensajes).
>
> Mis planes son:
>
> Extender el chat para incluir un ID para cada mensajes:
> Implementar transacciones PDO en el servidor, para evitar inserciones
simultáneas y no poder recuperar el ID (
https://github.com/Push-EDX/flarum-ext-chat/blob/master/src/Api/Controllers/FetchChatController.php#L73
)
> Enviar siempre la combinación (id, actorId, message) a los clientes, en
vez de solo (actorId, message) (vease ChatPost.php, ChatPostController).
> El cliente tendŕia que guardar también ese ID, implica pequeños cambios a
js/forum/src/main.js
> La API chat/fetch deberá además pedir un ID (
https://github.com/Push-EDX/flarum-ext-chat/blob/master/src/Api/Controllers/FetchChatController.php#L87
)
> Donde -1 sería los 20 últimos
> Cualquier otro valor el punto des del que cargar
>
> Evidentemente también faltaría toda la parte de UX para el feedback al
usuario
>
> Subir arriba de todo del chat mostrará un icono de cargando (puede servir
el mismo de enviar)
>
> Calculo que esto puede llevar unas 3 horas para hacerse, pero yo ahora
estaré de exámenes así que no podré hacerlo hasta la semana que viene
