### ISSUE TITLE
Sonido al recibir mensajes

### ISSUE THREAD

**Issue by gpascualg** [Push-EDX/flarum-ext-chat#2]
Cuando se recibe un mensaje iría bien tener una pequeña alerta sonora.

Es posible que #1 ya lo haga por defecto?

**Comment by Blaron** [comment]
```
var sound = Notification.sound;
var options = {
  body: 'Do you like my body?',
  sound: 'audio/alert.mp3'
}

var n = new Notification('Test notification',options);

n.sound // should return 'audio/alert.mp3' 

```
Src: https://developer.mozilla.org/es/docs/Web/API/notification/sound

**Comment by gpascualg** [comment]
@Blaron mola la idea pero más abajo pone que no hay soporte aún de ningún navegador para esto... Habría que probarlo por eso, porque me extrañaría que no lo tuvieran.

De todos modos, para poder lanzar notificaciones primero habría que obtener el permiso, se solapa con #1 (la parte básica). Quizás haciendo #1 ya solucionamos esta
