### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by sulf1ron** [Push-EDX/flarum-ext-chat#31]
I‘m using MySQL but this extension seems to use sqlite.
Is there a way to modify it to use MySQL?
Or can you please make a MySQL version?
Thank you very much.

**Comment by gpascualg** [comment]
As per PR https://github.com/Push-EDX/flarum-ext-chat/pull/29 it should no longer use SQLite but MySQL. I might have forgotten to bump the version.

Can you confirm it is the case?

**Comment by sulf1ron** [comment]
` {
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "PDOException: could not find driver in /var/www/forum/vendor/push-edx/flarum-ext-chat/src/Api/Controllers/FetchChatController.php:49\nStack trace:\n#0 /var/www/forum/vendor/push-edx/flarum-ext-chat/src/Api/Controllers/FetchChatController.php(49): PDO->__construct('sqlite:/tmp/cha...')\n#1 `

In push-edx/flarum-ext-chat/src/Api/Controllers/FetchChatController.php Line 49:
` $db = new PDO('sqlite:/tmp/chatposts.db');`

But in GitHub I find the file has been changed.
Maybe you haven't update it to composer.

**Comment by sulf1ron** [comment]
I clone from github and now it works.

**Comment by gpascualg** [comment]
Then I must have forgotten to push the new version to packagist. I'll keep this issue open until I do it, thank you!

**Comment by gpascualg** [comment]
Just pushed 0.6.0
