### ISSUE TITLE
Error When Enabling Plug-In

### ISSUE THREAD

**Issue by hifihedgehog** [Push-EDX/flarum-ext-chat#35]
I receive the following error when enabling this plug-in. "Something went wrong while trying to load the full version of this site." I do not receive this error with any other plug-in. I disabled all my other plug-ins and still cannot seem to get this to work. Documentation appears to be sparse. What special requirements are necessary to get this to work?

**Comment by gpascualg** [comment]
@hifihedgehog Can you take a look at your php logs? Which flarum version are you running?

**Comment by hifihedgehog** [comment]
The latest beta release.

**Comment by gpascualg** [comment]
@hifihedgehog The package requires (or should require) pusher ext., but enabling it can not be forced (as far as I know). Maybe we could check for it before trying to use it, and warn the admin (how?)

You should be able to change the title from the files inside "locale", not code at all.

As for the mobile version, it is designed to be hidden unless showing the menu, and it should show quite fine (at least it did). Isn't it working?

**Comment by hifihedgehog** [comment]
> You should be able to change the title from the files inside "locale", not code at all.
Thanks!
>As for the mobile version, it is designed to be hidden unless showing the menu, and it should show quite fine (at least it did). Isn't it working?

It is, actually. I just have an iPhone SE which has a small screen. It seems to be working fine after all.
